config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: "sessions",
      registrations: "registrations"
    },
    path_names: {
      sign_in: "login",
      sign_out: "logout",
      registration: "register",
      sign_up: "sign_up"
    }

  root to: "posts#index"

  resources :posts do
    resources :comments, except: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :user_id, :post_id, :content, presence: true

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, :title, :content, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable

  validates :email,
    presence: true, uniqueness: true, allow_blank: false, case_sensitive: false,
    format: { with: %r'\A(?:[^@\s]+)\@(?:[^@\s]+?)(\.[a-z]{2,})\z'xo }

  validates :password, presence: true
  validates :password, format: {
    with: %r'\A\S{8,}\z',
    message: I18n.t("activerecord.errors.models.user.attributes.password.format")
  }, if: -> { password.present? }

  validate  :matching_password_confirmation, if: -> { password.present? }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  private

  def matching_password_confirmation
    if password != password_confirmation
      errors.add(:password_confirmation, :confirmation)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:edit, :create, :update, :destroy]
  before_action :set_comment, only: [:edit, :update, :destroy]

  # GET /posts/:post_id/comments/:id/edit
  def edit
    authorize @comment

    render :edit
  end

  # POST /posts/:post_id/comments
  def create
    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))

    if @comment.save
      redirect_to @post, flash: { success: I18n.t("flash.comment.create.success") }
    else
      redirect_to @post, flash: { error: I18n.t("flash.comment.create.fail") }
    end
  end

  # PATCH/PUT /posts/:post_id/comments/:id
  def update
    authorize @comment

    if @comment.update(comment_params)
      redirect_to @post, flash: { success: I18n.t("flash.comment.update.success") }
    else
      render :edit
    end
  end

  # DELETE /posts/:post_id/comments/:id
  def destroy
    authorize @comment

    if @comment.destroy
      redirect_to @post, flash: { success: I18n.t("flash.comment.destroy.success") }
    else
      redirect_to @post, flash: { error: I18n.t("flash.comment.destroy.fail") }
    end
  end

  private

  def set_post
    @post ||= Post.find(params[:post_id])
  end

  def set_comment
    @comment ||= Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/:id
  def show
    @comment = Comment.new(user: current_user)
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/:id/edit
  def edit
    authorize @post

    render :edit
  end

  # POST /posts
  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, flash: { success: I18n.t("flash.post.create.success") }
    else
      render :new
    end
  end

  # PATCH/PUT /posts/:id
  def update
    authorize @post

    if @post.update(post_params)
      redirect_to @post, flash: { success: I18n.t("flash.post.update.success") }
    else
      render :edit
    end
  end

  # DELETE /posts/:id
  def destroy
    authorize @post

    if @post.destroy
      redirect_to posts_path, flash: { success: I18n.t("flash.post.destroy.success") }
    else
      redirect_to posts_path, flash: { error: I18n.t("flash.post.destroy.fail") }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  layout "sessions"
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  layout "sessions"
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    Rails.application.class.parent.to_s.freeze
  end

  def flash_class(level)
    case level
    when "notice" then "alert-info"
    when "success" then "alert-success"
    when "error" then "alert-danger"
    when "alert" then "alert-danger"
    end
  end
end

app/views/comments/_comment.html.erb
<div class="card mb-2">
  <div class="card-body">
    <h5 class="card-title"><%= comment.user.email %></h5>
    <p class="card-text"><%= comment.content %></p>
  </div>

  <div class="card-footer text-muted text-right">
    <% if policy(comment).update? %>
      <%=
        link_to(
          I18n.t("buttons.edit"),
          edit_post_comment_path(comment.post, comment),
          class: "btn btn-sm btn-light"
        )
      %>
    <% end %>
    <% if policy(comment).destroy? %>
      <%=
        link_to(
          I18n.t("buttons.delete"),
          post_comment_path(comment.post, comment),
          method: :delete,
          data: { confirm: I18n.t("confirm_delete") },
          class: "btn btn-sm btn-light"
        )
      %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [post, comment] do |form| %>
  <% comment.errors.any? && comment.errors.full_messages.each do |message| %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="card mb-2">    
    <div class="card-body">
      <p class="card-text">
        <div class="form-group">
          <%= form.label :content, class: "form-label" %>
          <%= form.text_area :content, id: :post_content, rows: "3", class: "form-control" %>
        </div>
      </p>
    </div>
    
    <div class="card-footer text-muted text-right">
      <%= form.submit I18n.t("buttons.save"), class: "btn btn-sm btn-primary" %>
      <% if ["edit", "update"].include?(action_name) %>
        <%= link_to I18n.t("buttons.back"), post_path(post), class: "btn btn-sm btn-light" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= render "form", post: @post, comment: @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title><%= app_name %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
</head>

<body class="bg-light">
  <%= render "shared/navbar" %>

  <div class="container">
    <div class="row">
      <div class="col-sm-8 offset-sm-1 col-md-8 offset-md-2">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title><%= app_name %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>

  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
</head>

<body class="bg-light">

  <div id="session" class="container-fluid">
    <div class="row mt-4">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for post do |form| %>
  <% post.errors.any? && post.errors.full_messages.each do |message| %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="card mb-2">
    <div class="card-header">
      <div class="form-group">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, id: :post_title, class: "form-control" %>
      </div>
    </div>
    
    <div class="card-body">
      <p class="card-text">
        <div class="form-group">
          <%= form.label :content, class: "form-label" %>
          <%= form.text_area :content, id: :post_content, rows: "3", class: "form-control" %>
        </div>
      </p>
    </div>
    
    <div class="card-footer text-muted text-right">
      <%= form.submit I18n.t("buttons.save"), class: "btn btn-sm btn-primary" %>
      <%= link_to I18n.t("buttons.back"), posts_path, class: "btn btn-sm btn-light" %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card mb-4">
  <div class="card-header"><%= post.user.email %>  </div>
  
  <div class="card-body">
    <h5 class="card-title"><%= post.title %></h5>
    <p class="card-text"><%= post.content %></p>
    <% if action_name == "index" %>
      <span class="card-link text-muted"><%= "Comments: #{post.comments.size}" %></span>
    <% end %>
  </div>
  
  <div class="card-footer text-muted text-right">
    <% if action_name == "index" %>
      <%= link_to I18n.t("buttons.show"), post, class: "btn btn-sm btn-light" %>
    <% end %>
    <% if policy(post).update? %>
      <%= link_to I18n.t("buttons.edit"), edit_post_path(post), class: "btn btn-sm btn-light" %>
    <% end %>
    <% if policy(post).destroy? %>
      <%=
        link_to(
          I18n.t("buttons.delete"),
          post_path(post),
          method: :delete,
          data: { confirm: I18n.t("confirm_delete") },
          class: "btn btn-sm btn-light"
        )
      %>
    <% end %>
    <% unless action_name == "index" %>
      <%= link_to I18n.t("buttons.back"), posts_path, class: "btn btn-sm btn-light" %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<% flash.each do |key, value| %>
  <div class="alert <%= flash_class(key) %> alert-dismissible fade show" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<%= render partial: "post", collection: @posts %>

<%= link_to fa_icon("plus"), new_post_path, class: "btn btn-primary floating-action" %>

app/views/posts/new.html.erb
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert <%= flash_class(key) %> alert-dismissible fade show" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<%= render "post", post: @post %>

<% unless action_name == "index" %>
  <h6>Comments:</h6>
  <%= render partial: "/comments/comment", collection: @post.comments %>
  <%= render "/comments/form", post: @post, comment: @comment %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between mb-4">
  <%= link_to app_name, root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse"
    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">

    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <div class="navbar-brand">
          <%= current_user.email %>
        </div>
      </li>
      <li class="nav-item">
        <div class="navbar-brand">
          <%= link_to fa_icon("power-off"), destroy_user_session_path, class: "logout-link" %>
        </div>
      </li>
    </ul>
  </div>
</nav>